// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var SIZE, canvas, canvasElement, count, ctx, img, loading, rotate, rotateImage;
    canvasElement = $('#canvas');
    canvas = canvasElement[0];
    ctx = canvas.getContext('2d');
    loading = $('#loading');
    rotate = [90, 180, 270, 360];
    count = 0;
    SIZE = 200;
    rotateImage = function() {
      var data, rad;
      loading.html('通信中...');
      if (count > 3) {
        count = 0;
      }
      rad = rotate[count++] * Math.PI / 180;
      ctx.clearRect(0, 0, SIZE, SIZE);
      ctx.save();
      ctx.setTransform(Math.cos(rad), Math.sin(rad), -Math.sin(rad), Math.cos(rad), SIZE / 2, SIZE / 2);
      ctx.translate(-1 * SIZE / 2, -1 * SIZE / 2);
      ctx.drawImage(img, 0, 0);
      ctx.restore();
      data = canvas.toDataURL('image/jpeg');
      return $.post('upload.php', {
        image: data
      }).done(function() {
        console.log('done');
        return loading.html('完了');
      });
    };
    $('#rotate').on('click', function(e) {
      e.preventDefault();
      return rotateImage();
    });
    img = new Image();
    img.onload = function() {
      return ctx.drawImage(img, 0, 0);
    };
    return img.src = 'hisasann.jpeg';
  });

}).call(this);
